'''
DESCRIPTION:
Project Euler, problem 44
Gregory Gundersen, ../../2013

PROBLEM:
Pentagonal numbers are generated by the formula, P_n = n(3n-1)/2.
The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8.
However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P_j and P_k, for which their sum and
difference is pentagonal and D = |P_k - P_j| is minimised; what is the value of D?

SOLUTION:
'''

import time
import gmath as g

pns = []
for i in range(1, 10000):
    pns.append(g.get_pentagonal_number(i))

for p1 in pns:
    for p2 in pns:
        p3 = p1 + p2
        p4 = p2 - p1

        if ((p3 in pns) and (p4 in pns)):
            print p1
            print p2
            print

print 'end'
